---
title: "03.7 Prediction"
output: html_document
params: 
  tfName: 
    label: "tfName"
    value: ATF2
  cofactors:
    label: "cofactors"
    value: ATF3
  predContext:
    label: "predContext"
    value: !r c("A549")
  maePath:
    label: "maePath"
    value: mae
  profilesPath:
    label: "profilesPath"
    value: "./profiles/ATF2_profile.tsv"
  outDir: 
    label: "outDir"
    value: "./out"
  modelPath:
    label: "modelPath"
    value: ""
  serial:
    label: "serial"
    value: TRUE
  seed:
    label: "seed"
    value: 42
---

```{r, setup}
suppressPackageStartupMessages({
  library(BSgenome.Hsapiens.UCSC.hg38)
  library(TFBlearner)
  library(data.table)
  library(BiocParallel)
  library(R.utils)
})
print(Sys.time())
```

```{r, rounding helper function}
roundNonZero <- function(x, digits=3){
  nonZeroInd <- which(x!=0)
  signs <- sign(x)
  xp <- round(x, digits=3)
  xp[nonZeroInd] <- pmax(xp[nonZeroInd], 10^-digits)
  xp <- signs*xp
  return(xp)
}
```

## Parameters

```{r, parameters, error=TRUE}
seed <- params$seed
set.seed(seed)

numThreads <- min(16, getDTthreads())
setDTthreads(numThreads)
RcppML::setRcppMLthreads(numThreads)

tfName <- params$tfName
profilesPath <- params$profilesPath

if(file.exists(profilesPath)){
  if(grepl(".tsv", profilesPath)){
    profile <- fread(profilesPath)
  }
  else{
    profile <- readRDS(profilesPath)
  }
  profile <- list(profile)
  names(profile) <- tfName
}else{
  profile <- readRDS(file.path(outDir, "profile.rds"))
}

modelPath <- params$modelPath
predContexts <- params$predContext
print(predContexts)

outDir <- params$outDir
if(!dir.exists(outDir)) dir.create(outDir)

predSerial <- params$serial
predBatched <- fifelse(!predSerial, TRUE, FALSE)
```

# Load inputs

```{r, prepare meta data, error=TRUE}
mae <- readRDS(params$maePath)
trainingContexts <- getContexts(mae, tfName=tfName, which="Both")

tfCofactors <- params$cofactors
tfCofactors <- unique(tfCofactors)
if(length(tfCofactors)==0 || all(gsub(' ', '',tfCofactors)=="")) tfCofactors <- NULL
tfCofactors <- setdiff(tfCofactors, tfName)
tfCofactors

models <- loadModels(modelPath)

conTFfeatures <- c("Inserts", "Weighted_Inserts", "ChromVAR_Scores")
if(length(trainingContexts)==1){
  conTFfeatures <- setdiff(conTFfeatures, "ChromVAR_Scores")
}
gc()
```

# Predict

```{r, predict batched, eval=predBatched, error=TRUE}
experiments(mae)$contextTfFeat <- NULL

setDTthreads(16)
batchSize <- 2
ptm <- proc.time()
for(i in seq(1,length(predContexts), batchSize)){
  predContextsBatch <- predContexts[i:min((i+batchSize-1),length(predContexts))]
  ptm3 <- proc.time()
  fms <- bplapply(predContextsBatch, function(context){
     mae <- contextTfFeatures(mae, 
                              tfName=tfName,
                              whichCol="Col",
                              colSel=context,
                              features=conTFfeatures,
                              addLabels=FALSE,
                              insertionProfile=profile,
                              seed=seed,
                              BPPARAM=SerialParam())
    fmPred <- getFeatureMatrix(mae, tfName=tfName,
                                    whichCol="Col", 
                                    colSel=context, 
                                    addLabels=FALSE,
                                    saveHdf5=FALSE)
    return(fmPred)},  
    BPPARAM=MulticoreParam(workers=batchSize, timeout=300, force.GC=TRUE))
  print(proc.time()-ptm3)
  gc()
      
  ptm2 <- proc.time()
  mapply(function(fm, context){
    predCon <- predictTfBinding(models, fm, 
                                chunk=NULL,
                                simplified=FALSE,
                                sparsify=TRUE,
                                BPPARAM=SerialParam())
    rm(fm)
    preds <- as.data.table(as.matrix(predCon[,c("pred_stacked",
                                                "pred_all_pos",
                                                "pred_stacked_binarized")]))
    rm(predCon)
    preds[,pred_stacked:=roundNonZero(pred_stacked, digits=3)]
    preds[,pred_all_pos:=roundNonZero(pred_all_pos, digits=3)]

    if(context %in% trainingContexts){
        lab <- assays(mae[["ChIP"]])$peaks[,paste(context, tfName, sep="_")]
        lab <- roundNonZero(lab, digits=2)
        preds <- cbind(preds, lab)}
  
    predFilePath <- file.path(outDir,
                              paste0(paste("pred", context, tfName, sep="_"),
                                         ".tsv"))
    write.table(preds, predFilePath, quote=FALSE, sep="\t", row.names=FALSE)
    gzip(predFilePath, overwrite=TRUE)
    return(NULL)}, fms, predContextsBatch)
  rm(fms)
  gc()
  print(proc.time()-ptm2)
}
print(proc.time()-ptm)
gc()
```

```{r, predict batched serial, eval=predSerial, error=TRUE}
experiments(mae)$contextTfFeat <- NULL
setDTthreads(16)
ptm <- proc.time()

for(context in predContexts){
  ptm4 <- proc.time()
  mae <- contextTfFeatures(mae, 
                           tfName=tfName,
                           whichCol="Col",
                           colSel=context,
                           features=conTFfeatures,
                           addLabels=FALSE,
                           insertionProfile=profile,
                           seed=seed,
                           BPPARAM=MulticoreParam(workers=8))
  print(proc.time()-ptm4)
  gc()
  
  ptm <- proc.time()
  fmPred <- getFeatureMatrix(mae, tfName=tfName,
                                  whichCol="Col", 
                                  colSel=context,
                                  addLabels=FALSE,
                                  saveHdf5=FALSE)
  experiments(mae)$contextTfFeat <- NULL
  print(proc.time()-ptm)
  
  gc()
  ptm <- proc.time()
  predCon <- predictTfBinding(models, fmPred, 
                              chunk=NULL,
                              simplified=FALSE,
                              sparsify=TRUE,
                              BPPARAM=SerialParam())
  print(proc.time()-ptm)
  gc()
  preds <- as.data.table(as.matrix(predCon[,c("pred_stacked",
                                              "pred_all_pos",
                                              "pred_stacked_binarized")]))
  preds[,pred_stacked:=roundNonZero(pred_stacked, digits=3)]
  preds[,pred_all_pos:=roundNonZero(pred_all_pos, digits=3)]
    
  rm(predCon)
  if(context %in% trainingContexts){
      lab <- assays(mae[["ChIP"]])$peaks[,paste(context, tfName, sep="_")]
      lab <- roundNonZero(lab, digits=2)
      preds <- cbind(preds, lab)}
  
  predFilePath <- file.path(outDir,
                            paste0(paste("pred", context, tfName, sep="_"),
                                         ".tsv"))
  write.table(preds, predFilePath, quote=FALSE, sep="\t", row.names=FALSE)
  gzip(predFilePath, overwrite=TRUE)
  gc()
}
print(proc.time()-ptm)
gc()
```

```{r, clean up}
expPredFiles <- file.path(outDir,
                          paste0(paste("pred", predContexts, tfName, sep="_"),
                                       ".tsv.gz"))
if(all(file.exists(expPredFiles))){
  file.remove(params$maePath)}
```

```{r, save version}
if(all(file.exists(expPredFiles))){
  con <- file("../CHANGELOG.md","r")
  predVersion <- readLines(con, n=1)
  close(con)
  predVersion <- unlist(tstrsplit(predVersion, split="[", keep=2, fixed=TRUE))
  predVersion <- unlist(tstrsplit(predVersion, split="]", keep=1, fixed=TRUE))
  versionDt <- data.table(run_version=predVersion,
                          TFBlearner_version=packageVersion("TFBlearner"))
  
  write.table(versionDt, sep="\t", 
              file=file.path(outDir, "version.tsv"),
              quote=FALSE, row.names=FALSE)
}
```

```{r, sessionInfo}
print(Sys.time())
sessionInfo()
```
