---
title: "02.2 Train-Test-Split"
output: html_document
date: "2025-21-01"
params: 
  metaDataPath: 
    label: metaDataPath
    value: "meta.tsv"
  outDir:
    label: "outDir"
    value: ./outDir
---

```{r, setup}
library(data.table)
library(knitr)
```

Import metadata:
```{r}
meta <- readRDS(params$metaDataPath)
outDir <- params$outDir
```

```{r, results="asis"}
metaAg <- meta[,.(n_chIP_peak_files=sum(!is.na(unique(chip_path_re))),
                  n_tfs=sum(!is.na(unique(tf_name))),
                  n_atac_files=sum(!is.na(unique(atac_path))),
                  n_caller=sum(!is.na(unique(caller)))), 
               by=.(context)]
setorder(metaAg, context)
# subset(metaAg, n_tfs>0)
kable(metaAg, title="captured celullar contexts")
```

Test cellular contexts: Embryonic stem cells & jurkat
```{r, split of test}
test <- subset(meta, grepl("jurkat", context, ignore.case=TRUE) | 
                     grepl("WA", context, ignore.case=TRUE) |
                     grepl("embryonic", context, ignore.case=TRUE) | 
                     grepl("ESC", context, ignore.case=TRUE))
unique(subset(test,is_matched)$context_id)
unique(subset(test, is_matched)$tf_name)

train <- meta[!test, on=c("context_id", 
                          "db_id_ATAC", 
                          "db_id_chIP")]

saveRDS(train, file.path(outDir, "03_trainMetaAll.rds"))
saveRDS(test, file.path(outDir, "03_testMetaAll.rds"))
```

```{r, sessioninfo}
sessionInfo()
```
