---
title: "02.3 Labels & Weights"
output: html_document
date: '2024-07-05'
params: 
  metaTrainPath:
    label: "metaTrainPath"
    value: "metaTrainPath.tsv"
  metaChIPPath:
    label: "metaChIPPath"
    value: "metaChIP.tsv"
  refCoordsPath:
    label: "refCoordsPath"
    value: "refCoords.rds"
  outDirMeta: 
    label: "outDirMeta"
    value: ./outDirMeta
  outDirChIP: 
    label: "outDirChIP"
    value: ./outDirChIP
---

```{r, setup}
suppressPackageStartupMessages({
  library(BiocParallel)
  library(data.table)
  library(gam)
  library(GenomicRanges)
  library(ggplot2)
  library(Matrix)
  library(MatrixGenerics)
  library(TFBlearner)
  source("utils.R")
})

seed <- 42
set.seed(seed)
```

```{r, paths}
outDirMeta <- params$outDirMeta
if(!dir.exists(outDirMeta)) dir.create(outDirMeta)

outDir <- params$outDirChIP
if(!dir.exists(outDir)) dir.create(outDir)

metaTrainData <- readRDS(params$metaTrainPath)
metaDataChIP <- readRDS(params$metaChIPPath)

metaDataChIP <- subset(metaDataChIP, 
                       combination_id %in% metaTrainData$combination_id)

refCoords <- readRDS(params$refCoordsPath)
```

```{r, determine replicated experiments}
metaDataChIP[,n_exp:=length(unique(db_id_chIP)), by=combination_id]
```

```{r, setup training matrix, error=TRUE, warning=FALSE, eval=TRUE}
metaChIPRep <- subset(metaDataChIP, n_exp>=2)
repCombs <- unique(metaChIPRep$combination_id)

repStats <- getLabels(repCombs, metaChIPRep, refCoords, subset=TRUE)
```

```{r, train models, error=TRUE, eval=TRUE}
repDt <- lapply(repStats, function(e) e$repDt)
repDt <- rbindlist(repDt)

corsDt <- lapply(repStats, function(e) as.data.table(e$corsPICS, 
                                                     keep.rownames=TRUE))
corsDt <- rbindlist(corsDt)
colnames(corsDt) <- c("caller", "spearman_cor")
corsDt[,caller:=tstrsplit(caller, split=".", fixed=TRUE, keep=2)]

corsDt <- subset(corsDt, !is.na(spearman_cor))
ggplot(corsDt, aes(x=caller, y=spearman_cor))+
  geom_boxplot()

ggplot(repDt, aes(x=label_rep, y=qValue))+
  geom_boxplot()+
  scale_y_log10()

ggplot(repDt, aes(x=is_uncertain, y=qValue))+
  geom_boxplot()+
  scale_y_log10()

ggplot(repDt, aes(x=is_only_PICS, y=qValue))+
  geom_boxplot()+
  scale_y_log10()
```

```{r, fit gam, error=TRUE, eval=TRUE}
repDt <- subset(repDt, is.finite(qValue))
testInd <- sample(1:nrow(repDt), 1e4)
repTrainDt <- repDt[setdiff(1:nrow(repDt), testInd)]
repTestDt <- repDt[testInd,]

mod <- gam::gam(label_rep ~ s(qValue, spar=0.6), 
                data=repTrainDt, family="binomial")

predTest <- predict(mod, 
                    as.data.frame(as.matrix(repTestDt)), 
                    type="response")
repTestDt$pred <- predTest
repTestDt$model <- "gam"

aucPrPred <- TFBlearner:::.getRocs(repTestDt, scores="pred", 
                                   posClass=TRUE, negClass=FALSE,
                                   labels="label_rep", models="model",
                                   seed=seed)
unique(aucPrPred$auc_pr_mod)
aucPrQval <- TFBlearner:::.getRocs(repTestDt, scores="qValue", 
                                   posClass=TRUE, negClass=FALSE,
                                   labels="label_rep", models="model",
                                   seed=seed)
unique(aucPrQval$auc_pr_mod)
```

```{r, plot gam, error=TRUE}
plot.Gam(mod, se=TRUE)
```

```{r, save model, error=TRUE, eval=TRUE}
saveRDS(mod, file.path(outDirMeta, "gam_rep.rds"))
```

```{r, reprocess, warning=FALSE, error=TRUE}
allCombs <- unique(metaDataChIP$combination_id)
fns <- lapply(allCombs, function(comb){
  res <- getLabels(c(comb), metaDataChIP, refCoords, 
                   subset=FALSE, annotate=TRUE)
  labelDt <- res[[1]]$repDt
  labelDt$rep_prob <- predict(mod, 
                              newdata=data.frame(qValue=labelDt$qValue), 
                              type="response")
  labelDt[,rep_prob:=fifelse(label_rep,1,rep_prob)]
  labelDt[,rep_prob:=fifelse(is_uncertain, 1, rep_prob)]

  metaSub <- subset(metaDataChIP, combination_id==comb)
  fn <- paste(comb, unique(metaSub$tf_name), 
                    unique(metaSub$context_id),
             "label.rds", sep="_")
  saveRDS(labelDt, file.path(outDir, fn))
  return(fn)
})

metaLabel <- data.table(file_name=unlist(fns))
metaLabel[,file_path:=file.path(outDir, file_name)]
metaLabel[,c("combination_id", 
             "tf_name",
             "cellular_context_id"):=tstrsplit(file_name, split="_", keep=1:3)]
saveRDS(metaLabel, file.path(outDirMeta, "04_trainMetaChIPAll.rds"))
```

```{r, sessioninfo}
sessionInfo()
```
