---
title: "02.8 Insertion profiles"
output: html_document
params: 
  maePath:
    label: "maePath"
    value: ./mae.rds
  metaObjectPath:
    label: "metaObjectPath"
    value: ./mae_meta.rds  
  tfsListPath:
    label: "tfsListPath"
    value: "tfsListPath.tsv"
  seed:
    label: "seed"
    value: 42
  metaDir:
    label: "metaDir"
    value: ./metaData
  motifDir: 
    label: "motifDir"
    value: ./motifData
  outDir:
    label: "outDir"
    value: ./insertions
---

```{r, setup}
suppressPackageStartupMessages({
  library(BSgenome.Hsapiens.UCSC.hg38)
  library(ggplot2)
  library(viridis)
  library(patchwork)
  library(RColorBrewer)
  library(TFBlearner)
})
seed <- params$seed
set.seed(seed) # only needed when subsampling
```

```{r, paths}
allTfs <- readRDS(params$tfsListPath)
maePath <- params$maePath
metaMaePath <- params$metaObjectPath

metaDir <- params$metaDir
motifDir <- params$motifDir
outDir <- params$outDir
if(!dir.exists(outDir)) dir.create(outDir)
```

```{r, load mae data}
mae <- readRDS(maePath)
metaMae <- readRDS(metaMaePath)
```


# Calculate Profile for each cellular context X Tf

```{r, per context profiles, eval=TRUE}
maxScores <- colData(mae[["Motifs"]])[,c("motifName", "maxScore")]
maxScores <- as.data.table(maxScores)
maxScores[,maxScore:=maxScore/TFBlearner:::scalFactMotif]

# subset to training only data
cols <- lapply(experiments(mae), function(n) {
        colnames(n)[colnames(n) %in% unique(subset(sampleMap(mae), 
            isTraining)$colname)]})
mae <- subsetByColumn(mae, cols)
basePath <- metadata(colData(experiments(mae)$ATAC))$baseDir
atacMeta <- as.data.table(subset(colData(experiments(mae)$ATAC)))
refCoords <- rowRanges(mae[["ATAC"]])

metaMatched <- subset(metaMae, is_matched & type=="train")
allTfs <- intersect(allTfs, unique(metaMatched$tf_name))

lapply(allTfs, function(tfI){
  tryCatch({
  contexts <- unique(subset(metaMatched, tf_name==tfI)$full_id)
  motifFileName <- file.path(motifDir, paste0(tfI, ".rds"))
  
  allInsConsFiles <- file.path(outDir, paste0(paste(tfI, contexts, sep="_"), ".rds"))
  if(file.exists(motifFileName) & 
     length(contexts)>0 & 
     !all(file.exists(allInsConsFiles))){
    maxScore <- subset(maxScores, motifName==tfI)$maxScore
    motifMatches <- readRDS(file.path(motifDir, paste0(tfI, ".rds")))
    motifMatches <- motifMatches[motifMatches$score>=(maxScore/2)]
    seqlevelsStyle(motifMatches) <- seqlevelsStyle(refCoords)
    motifMatches <- subsetByOverlaps(motifMatches, refCoords)}
  else{
    return(NULL)
  }
  
  lapply(contexts, function(contextI){
    if(file.exists(file.path(outDir, paste0(paste(tfI, contextI, sep="_"), ".rds")))){
      return(NULL)
    }
    atacPath <- file.path(basePath, 
                          unlist(unique(subset(atacMeta, context==contextI)$origin)))
    fragData <- lapply(atacPath, TFBlearner:::.processData, shift=FALSE)
    fragData <- rbindlist(fragData)
    
    # subset by overlapping ChIP-peak
    rs <- rowSums(assays(experiments(mae)$ChIP)$peaks[,paste(contextI,tfI, sep="_"),drop=FALSE])
    pki <- which(rs>0.5)
    motifSubMatches <- subsetByOverlaps(motifMatches,rowRanges(experiments(mae)$ChIP)[pki])

    if(length(motifSubMatches)>0){
      motifSubMatches$motif_id <- tfI
      ins <- suppressWarnings(getInsertionProfiles(atacData=fragData,
                                  motifRanges=motifSubMatches,
                                  margin=200,
                                  calcProfile=TRUE,
                                  stranded=TRUE,
                                  shift=FALSE,
                                  symmetric=FALSE))
      gc()
      saveRDS(ins$insertProfiles, 
              file.path(outDir, paste0(paste(tfI, contextI, sep="_"), ".rds")))
    return(NULL)}
    else{
      return(NULL)
    }
  })},
  error=function(cond){
    message(paste("Could not compute insertion profiles for", tfI))
    message(conditionMessage(cond))
    return(NULL)
  }
  )
})
```


# Insertion Profiles

```{r, mean/median profiles, eval=TRUE}
insFiles <- list.files(outDir)
insFiles <- insFiles[!grepl("median", insFiles) & !grepl("_plot", insFiles)]
insFiles <- data.table(file_name=insFiles)
insFiles[,c("tf", "context"):=tstrsplit(file_name, split="_", keep=1:2)]
insFiles[,context:=substr(context, 1, nchar(context)-4)]

profileMap <- data.table()
lapply(allTfs, function(tfI){
  subInsFiles <- subset(insFiles, tf==tfI & context %in% metaMatched$full_id)
  if(nrow(subInsFiles)>0){
    paths <- file.path(outDir, subInsFiles$file_name)
  
    profiles <- lapply(paths, readRDS)
    names(profiles) <- subInsFiles$context
  
    profiles <- rbindlist(profiles, idcol="context")
    profilesMean <- profiles[,.(w=median(w, na.rm=TRUE)), by=rel_pos]
    profilesMean[,w_smooth:=as.numeric(smooth(w, twiceit=TRUE))]
  
    profilesMean$context <- "median"
    medianProfilePlot <- ggplot(profiles, aes(x=rel_pos, y=w, group=context))+
      geom_line(color="darkgrey", alpha=0.7)+
      geom_line(color="grey",aes(x=rel_pos, y=w_smooth), alpha=0.7)+
      geom_line(data=profilesMean, mapping=aes(x=rel_pos, y=w, context="median"), 
              color="darkred")+
      geom_line(data=profilesMean, mapping=aes(x=rel_pos, y=w_smooth, context="median"), 
              color="red")+
      ggtitle(tfI)+
      theme_bw()
    ggsave(file.path(outDir, paste(tfI, "plot.png", sep="_")), medianProfilePlot)
  
    gc()
    profilePath <- file.path(outDir, paste(tfI, "median.rds", sep="_"))
    saveRDS(profilesMean, profilePath)
    profileIt <- data.table(tf=tfI, profile_path=profilePath)
    profileMap <- rbind(profileMap, profileIt, fill=TRUE, use.names=TRUE)
  }
  else{
    return(NULL)
  }
})

write.table(profileMap, file.path(metaDir, "profileMap.tsv"), sep="\t", 
            row.names=FALSE, quote=FALSE)
```
