---
title: "Compilation of hyperparameter data"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(data.table)
  library(lightgbm)
  library(BiocParallel)
  library(TFBlearner)
})
setDTthreads(4)
source("../utils/load_all.R", chdir=TRUE)
```


```{r}
hpFiles <- list.files("../data/predictions", recursive=TRUE, 
                        pattern="hyperParams_", full.names=TRUE)
names(hpFiles) <- basename(dirname(hpFiles))
hp <- bplapply(hpFiles, BPPARAM=SnowParam(20, progress=TRUE), function(hpFile){
  tf <- basename(dirname(hpFile))
  hp <- tryCatch({
    hp <- fread(hpFile)
    as.data.frame(hp)
  }, error=function(e){ NULL })
  if(is.null(hp)) return(NULL)
  hp$trainset <- hp$holdout_set <- NULL
  tryCatch({
    mod <- TFBlearner::loadModels(file.path(dirname(hpFile), 
                                  paste0(paste("model",tf, sep="_"), ".txt")))
    
    dt <- lgb.model.dt.tree(mod$all_pos)
    leafWeightsAllPos <- dt[is.na(split_feature), leaf_value]
    
    dt <- lgb.model.dt.tree(mod$all_weighted_pos)
    leafWeightsAllWeighted <- dt[is.na(split_feature), leaf_value]
    
    dt <- lgb.model.dt.tree(mod$med_weighted_pos)
    leafWeightsMedWeighted <- dt[is.na(split_feature), leaf_value]

    dt <- lgb.model.dt.tree(mod$top_weighted_pos)
    leafWeightsTopWeighted <- dt[is.na(split_feature), leaf_value]
    
    modDt <- data.frame(num_trees=c(mod$all_pos$num_trees(),
                                    mod$all_weighted_pos$num_trees(),
                                    mod$med_weighted_pos$num_trees(),
                                    mod$top_weighted_pos$num_trees()), 
                        ssw=c(sum(leafWeightsAllPos^2), 
                              sum(leafWeightsAllWeighted^2),
                              sum(leafWeightsMedWeighted^2),
                              sum(leafWeightsTopWeighted^2)),
                        asw=c(sum(abs(leafWeightsAllPos)),
                              sum(abs(leafWeightsAllWeighted)),
                              sum(abs(leafWeightsMedWeighted)),
                              sum(abs(leafWeightsTopWeighted))),
                        submodel=c("all_pos", "all_weighted_pos", 
                                   "med_weighted_pos", "top_weighted_pos"))
    merge(hp, modDt, by="submodel")
  }, error=function(e){
    hp$num_trees <- NA
    hp
  })
})
table((hpIsNull <- sapply(hp, is.null)))
hp <- dplyr::bind_rows(hp[!hpIsNull], .id="TF")
hp$sumLearning <- hp$learning_rate*hp$num_trees
hp$tree_complexity <- (1/2)*hp$lambda_l2*hp$ssw+hp$lambda_l1*hp$asw
saveRDS(hp, file="hyperparams.rds")
```

