---
title: "04.1 Model component ablations"
output: html_document
---

```{r, setup}
suppressPackageStartupMessages({
library(BiocParallel)
library(phastCons100way.UCSC.hg38)
library(BSgenome.Hsapiens.UCSC.hg38)
library(EnsDb.Hsapiens.v86)
library(TFBlearner)
library(ggplot2)
library(gam)})

seed <- 42 # params$seed
set.seed(seed)
```

```{r, setup data}
selectedTfs <- c("ELF1", "SMAD1",  # pioneers
                 "USF2", "ZNF292", # settlers
                 "FOS", "MEF2D") # migrants
holdOutChr <- c("chr2", "chr4", "chr9")
```

```{r, inputs}
mae <- readRDS("../data/04_maeAll_conFeat_sub.rds") 
cofactors <- readRDS("../data/meta_data/topInteractors.rds")
outDir <- "."
```

```{r, remove test data}
cols <- lapply(experiments(mae), function(n) {
        colnames(n)[colnames(n) %in% unique(subset(sampleMap(mae), 
             !isTesting)$colname)]})
mae <- subsetByColumn(mae, cols)
```

```{r, define paramgrid}
paramGrid <- data.table(tuneHyperparams=c(FALSE,TRUE,TRUE,TRUE,TRUE),
                        loContext=c(TRUE,FALSE,FALSE,TRUE,TRUE),
                        measure=c("classif.logloss",  # does not matter
                                  "classif.logloss", 
                                  "classif.aucpr",
                                  "classif.logloss",
                                  "classif.aucpr"))
paramGrid <- paramGrid[nrow(paramGrid):1,]

predCols <- c(paste(TFBlearner:::PREDPREFIX, TFBlearner:::MODELNAMES, sep="_"),
              paste(TFBlearner:::PREDPREFIX, TFBlearner:::MODELSTACKEDSUFFIX, sep="_"))
```

```{r, ablation rounds}
auprAllDt <- data.table()
hpAllDt <- data.table()
for(tf in selectedTfs){
  contexts <- getContexts(mae, tfName=tf, which="Both")
  tfCofactors <- unique(cofactors[[tf]])
  
  experiments(mae)$tfFeat <- NULL
  experiments(mae)$contextTfFeat <- NULL
  
  # Compute the tf-specific features
  mae <- tfFeatures(mae, 
                    tfName=tf,
                    tfCofactors=tfCofactors,
                    nPatterns=40,
                    nMotifs=10,
                    seed=seed)
  
  profile <- NULL
  mae <- contextTfFeatures(mae, tfName=tf, 
                           whichCol="OnlyTrain",
                           features=c("Inserts", 
                                      "Weighted_Inserts", 
                                      "ChromVAR_Scores"),
                           addLabels=TRUE, 
                           seed=seed,
                           profiles=profile)
  
  saveHdf5 <- fifelse(length(contexts)>1, TRUE, FALSE)
  fm <- getFeatureMatrix(mae, tfName=tf, 
                         addLabels=TRUE, 
                         whichCol="OnlyTrain", 
                         norm="robust", 
                         convertInteger=FALSE,
                         saveHdf5=saveHdf5)

  rangesFm <- rowRanges(fm)
  rangeDt <- as.data.table(rangesFm)
  rangeDt[,row_id:=1:.N]

  holdOutInd <- subset(rangeDt, seqnames %in% holdOutChr)$row_id
  holdOutRanges <- rangesFm[holdOutInd]

  # subset to autosomes
  trainInd <- subset(rangeDt, seqnames %in% paste0("chr", 1:22))$row_id
  trainInd <- setdiff(trainInd, holdOutInd)
  trainRanges <- rangesFm[trainInd]

  fmTrain <- IRanges::subsetByOverlaps(fm, trainRanges, type = "equal")
  fmValChrs <- IRanges::subsetByOverlaps(fm, holdOutRanges, type = "equal")
  
  if(nrow(fmValChrs)>4e6){
    fmValChrs <- fmValChrs[sample(1:nrow(fmValChrs), 4e6),]  
  }else{
    fmValChrs <- fmValChrs
  }
  assays(fmValChrs)$features <- TFBlearner:::.convertToMatrix(assays(fmValChrs)$features)
  
  # CV-Rounds (leave-one-context-out)
  for(context in contexts){
    # subset feature matrix
    fmValIt <- fmTrain[which(rowData(fmTrain)$context==context),]
    fmValChrsIt <- fmValChrs[which(rowData(fmValChrs)$context!=context),]
    assays(fmValIt)$features <- TFBlearner:::.convertToMatrix(assays(fmValIt)$features)
    fmTrainIt <- fmTrain[which(rowData(fmTrain)$context!=context),]
    
    # ablate components of model
    for(i in 1:nrow(paramGrid)){
          trainParams <- paramGrid[i,]
          
          ptm <- proc.time()
          BPPARAM <- SnowParam(workers=4, timeout=7200,
                     force.GC=TRUE, log=TRUE,logdir=".")
          bpstart(BPPARAM)
          bplapply(1:4, function(x) {
            suppressPackageStartupMessages({
            require(TFBlearner, attach.required=TRUE)
            })
          NULL}, BPPARAM = BPPARAM)
          mods <- trainTfModel(tfName=tf,
                               fm=fmTrainIt,
                               measureName=trainParams$measure[1],
                               evalRounds=100,
                               earlyStoppingRounds=5,
                               tuneHyperparams=trainParams$tuneHyperparams[1],
                               loContext=trainParams$loContext[1],
                               stackingStrat="wMean", 
                               seed=seed,
                               BPPARAM=BPPARAM)
          bpstop(BPPARAM)
          gc()
          ptm2 <- proc.time()
          
          # Predict on training data
          predsValCon <- predictTfBinding(mods, fmValIt, chunk=NULL, 
                                          simplified=FALSE, 
                                          BPPARAM=SerialParam())
          predsValCon <- as.data.table(as.matrix(predsValCon[predsValCon[,TFBlearner:::BINLABELNAME]>=0,]))
          prVal <- lapply(predCols, TFBlearner:::.getPRCurve, 
                          dt=predsValCon, 
                          labels=TFBlearner:::BINLABELNAME, models="context", 
                          posClass=1, negClass=0, subSample=FALSE, 
                          aggregate=TRUE, seed=seed)
          names(prVal) <- predCols
          prVal <- rbindlist(prVal, idcol="submodel")
          prVal$tfName <- tf
          prVal$pos_frac <- sum(predsValCon[[TFBlearner:::BINLABELNAME]])/nrow(predsValCon)
          prVal$computed <- "val_context"
          prVal$holdout_context <- context
          prVal$training_context <- paste(setdiff(contexts, context), collapse=".")
          
          # predict also for validation chromosomes
          predsValChr <- predictTfBinding(mods, fmValChrsIt, chunk=NULL, 
                                          simplified=FALSE, 
                                          BPPARAM=SerialParam())
          predsValChr <- as.data.table(as.matrix(predsValChr[predsValChr[,TFBlearner:::BINLABELNAME]>=0,]))
          prValChr <- lapply(predCols, TFBlearner:::.getPRCurve, 
                             dt=predsValChr, 
                             labels=TFBlearner:::BINLABELNAME, models="context", 
                             posClass=1, negClass=0, subSample=FALSE, 
                             aggregate=TRUE, seed=seed)
          names(prValChr) <- predCols
          prValChr <- rbindlist(prValChr, idcol="submodel")
          prValChr$tfName <- tf
          prValChr$pos_frac <- sum(predsValChr[[TFBlearner:::BINLABELNAME]])/nrow(predsValChr)
          prValChr$computed <- "val_chromosomes"
          prValChr$holdout_context <- context
          prValChr$training_context <- paste(setdiff(contexts, context), collapse=".")
          
          # bind iteration results and save
          auprDt <- rbind(prVal, prValChr, use.names=TRUE, fill=TRUE)
          auprDt$tuneHyperparams <- trainParams$tuneHyperparams[[1]]
          auprDt$loContext <- trainParams$loContext[[1]]
          auprDt$measure <- trainParams$measure[[1]]
          auprDt$elapsed <- (ptm2-ptm)[[3]]
          auprAllDt <- rbind(auprAllDt, auprDt, use.names=TRUE, fill=TRUE)
          write.table(auprAllDt, file=file.path(outDir, "performance_component_ablation.tsv"),
                      quote=FALSE, row.names=FALSE, sep="\t")
          
          hpDts <- lapply(mods[TFBlearner:::MODELNAMES], function(m){
            params <- m$params[setdiff(names(m$params), 
                                       c("preselMotif", "preselActMotif", 
                                         "interaction_constraints", "metric"))]
            as.data.table(params)})
          hpDt <- rbindlist(hpDts, idcol="submodel")
          hpDt$tuneHyperparams <- trainParams$tuneHyperparams[[1]]
          hpDt$loContext <- trainParams$loContext[[1]]
          hpDt$measure <- trainParams$measure[[1]]
          hpDt$elapsed <- (ptm2-ptm)[[3]]
          hpAllDt <- rbind(hpAllDt, hpDt, use.names=TRUE, fill=TRUE)
          write.table(hpAllDt, file=file.path(outDir, "hyperparameters_component_ablation.tsv"),
                      quote=FALSE, row.names=FALSE, sep="\t")
    }
  }
}
```

```{r, performance plots}
library(viridis)
auprAggDt <- auprAllDt[,.(aucpr_mean=mean(auc_pr_mod),
                          aucpr_median=median(auc_pr_mod)), 
                        by=.(tuneHyperparams, 
                             loContext, 
                             measure, 
                             tfName, 
                             computed,
                             submodel)]
auprAggDt <- subset(auprAggDt, submodel %in% c("pred_stacked", 
                                               "pred_all_weighted_pos",
                                               "pred_all_pos"))
auprAggDt[,submodel:=fifelse(submodel=="pred_all_pos", "unweighted", submodel)]
auprAggDt[,submodel:=fifelse(submodel=="pred_all_weighted_pos", "weighted", submodel)]
auprAggDt[,submodel:=fifelse(submodel=="pred_stacked", "stacked", submodel)]

ggplot(auprAggDt, aes(x=tfName,y=interaction(tuneHyperparams, 
                                              loContext, 
                                              measure), 
                      fill=aucpr_median))+
  geom_tile()+
  geom_text(aes(label=round(aucpr_median,2)), color="white")+
  scale_fill_viridis(option="A")+
  facet_grid(cols=vars(computed), rows=vars(submodel))+
  theme_bw()

ggplot(auprAggDt, aes(x=tfName,y=interaction(tuneHyperparams, 
                                              loContext, 
                                              measure), 
                      fill=aucpr_mean))+
  geom_tile()+
  geom_text(aes(label=round(aucpr_median,2)), color="white")+
  scale_fill_viridis(option="A")+
  facet_grid(cols=vars(computed), rows=vars(submodel))+
  theme_bw()
```

```{r, save best combination}
auprAggDt <- auprAllDt[,.(aucpr_mean=mean(auc_pr_mod),
                          aucpr_median=median(auc_pr_mod)), 
                        by=.(tuneHyperparams, 
                             loContext, 
                             measure, 
                             computed,
                             submodel)]
auprAggDt <- subset(auprAggDt, computed=="val_context" & submodel=="pred_stacked")
bestComb <- head(setorder(auprAggDt, -aucpr_mean), 1)
write.table(bestComb, file=file.path(outDir, "best_component_combination.tsv"),
            quote=FALSE, row.names=FALSE, sep="\t")
```

```{r}
sessionInfo()
```
