---
title: "04.2 Feature ablations"
output: html_document
---

```{r, setup}
suppressPackageStartupMessages({
library(BiocParallel)
library(phastCons100way.UCSC.hg38)
library(BSgenome.Hsapiens.UCSC.hg38)
library(EnsDb.Hsapiens.v86)
library(TFBlearner)
library(gam)})

seed <- 42 # params$seed
set.seed(seed)
```

```{r, setup data}
selectedTfs <- c("ATF3", "NR3C1", "MEF2C", "MYC", "ZNF143", "MAX", "JUN", "SOX6")
holdOutChr <- c("chr2", "chr4", "chr9")
```

```{r, inputs}
mae <- readRDS("../03_training_prediction/mae_context_features.rds") # "../data/03_maeAll_conFeat.rds"
cofactorMap <- fread("../data/meta_data/cofactorMaps.tsv")
setnames(cofactorMap, "tf", "tf_train")
outDir <- "." #params$outDir
```

```{r, remove test data}
cols <- lapply(experiments(mae), function(n) {
        colnames(n)[colnames(n) %in% unique(subset(sampleMap(mae), 
            !isTesting)$colname)]})
mae <- subsetByColumn(mae, cols)
```

```{r, define feature groups}
lDt <- listFeatures()
featureGroups <- lDt$feature_name
featureGroups <- setdiff(featureGroups, "Annot")
featureGroups <- c(featureGroups, "Embed", "footprint",
                   "distTSS")
featureGroups <- lapply(featureGroups, function(featureGroup){
                          if(!(featureGroup %in% c("Embed", 
                                                   "footprint", 
                                                   "distTSS"))){
                             subset(lDt, feature_name==featureGroup)$feature_matrix_column_names}
                          else{
                             list(featureGroup)}
})

predCols <- c(paste(TFBlearner:::PREDPREFIX, TFBlearner:::MODELNAMES, sep="_"),
              paste(TFBlearner:::PREDPREFIX, TFBlearner:::MODELSTACKEDSUFFIX, sep="_"))
```

```{r, read parameter combination}
selParams <- c()
```

```{r, ablation rounds}
auprAllDt <- data.table()
hpAllDt <- data.table()
for(tf in selectedTfs){
  tfCofactors <- unique(subset(cofactorMap, tf_train==tf)$tf_cofactor)
  
  # Compute the tf-specific features
  mae <- tfFeatures(mae, 
                    tfName=tf,
                    tfCofactors=tfCofactors,
                    nPatterns=20, # switch to 50
                    seed=seed)
  
  # load the profile (based on profileMap)
  # TODO: here!
  profile <- NULL
  mae <- contextTfFeatures(mae, tfName=tf, 
                           whichCol="OnlyTrain",
                           features=c("Inserts", 
                                      "Weighted_Inserts", 
                                      "ChromVAR_Scores"),
                           addLabels=TRUE, 
                           seed=seed,
                           profiles=profile)
  
  contexts <- getContexts(mae, tfName=tf, which="Both")
  saveHdf5 <- fifelse(length(contexts)>2, TRUE, FALSE)
  fm <- getFeatureMatrix(mae, tfName=tf, 
                         addLabels=TRUE, 
                         whichCol="OnlyTrain", 
                         saveHdf5=saveHdf5)

  rangesFm <- rowRanges(fm)
  rangeDt <- as.data.table(rangesFm)
  rangeDt[,row_id:=1:.N]

  holdOutInd <- subset(rangeDt, seqnames %in% holdOutChr)$row_id
  holdOutRanges <- rangesFm[holdOutInd]

  # subset to autosomes
  trainInd <- subset(rangeDt, seqnames %in% paste0("chr", 1:22))$row_id
  trainInd <- setdiff(trainInd, holdOutInd)
  trainRanges <- rangesFm[trainInd]

  fmTrain <- IRanges::subsetByOverlaps(fm, trainRanges, type = "equal")
  fmValChrs <- IRanges::subsetByOverlaps(fm, holdOutRanges, type = "equal")
  
  if(nrow(fmValChrs)>4e6){
    fmValChrs <- fmValChrs[sample(1:nrow(fmValChrs), 4e6),]  
  }else{
    fmValChrs <- fmValChrs
  }
  assays(fmValChrs)$features <- TFBlearner:::.convertToMatrix(assays(fmValChrs)$features)
  
  # CV-Rounds (leave-one-context-out)
  for(context in contexts){
  
    # subset feature matrix
    fmValIt <- fmTrain[which(rowData(fmTrain)$context==context),]
    fmValChrsIt <- fmValChrs[which(rowData(fmValChrs)$context!=context),]
    assays(fmValIt)$features <- TFBlearner:::.convertToMatrix(assays(fmValIt)$features)
    fmTrainIt <- fmTrain[which(rowData(fmTrain)$context!=context),]

    # ablate components of model
    for(featureGroup in featureGroups){
      
          # get the feature matrix column names
          colNamesAbl <- lapply(unlist(featureGroup), function(feature){
            colnames(fmTrain)[grepl(feature,colnames(fmTrain))]})
          colNamesAbl <- unlist(colNamesAbl)
    
          # subset to feature group
          assays(fmValIt)$features <- assays(fmValIt)$features[,setdiff(colnames(fmValIt), 
                                                                        colNamesAbl)]
          assays(fmValChrsIt)$features <- assays(fmValChrsIt)$features[,setdiff(colnames(fmValChrsIt), 
                                                                                colNamesAbl)]
          assays(fmTrainIt)$features <- assays(fmTrainIt)$features[,setdiff(colnames(fmTrainIt), 
                                                                            colNamesAbl)]
          
          BPPARAM <- SnowParam(workers=4, timeout=7200,
                     force.GC=TRUE, log=TRUE,logdir=".")
          bpstart(BPPARAM)
          bplapply(1:4, function(x) {
            suppressPackageStartupMessages({
            require(TFBlearner, attach.required=TRUE)
            })
          NULL}, BPPARAM = BPPARAM)
          mods <- trainTfModel(tfName=tf,
                               fm=fmTrainIt,
                               measureName=selParams$measure,
                               evalRounds=100,
                               earlyStoppingRounds=5,
                               tuneHyperparams=selParams$tuneHyperparams,
                               loContext=selParams$loContext,
                               stackingStrat="wMean", 
                               BPPARAM=BPPARAM)
          bpstop(BPPARAM)
          gc()
          
          # Predict on training data
          predsValCon <- predictTfBinding(mods, fmValIt, chunk=NULL, 
                                          simplified=FALSE, 
                                          BPPARAM=SerialParam())
          predsValCon <- as.data.table(as.matrix(predsValCon[predsValCon[,TFBlearner:::BINLABELNAME]>=0,]))
          prVal <- lapply(predCols, TFBlearner:::.getPRCurve, 
                          dt=predsValCon, 
                          labels=TFBlearner:::BINLABELNAME, models="context", 
                          posClass=1, negClass=0, subSample=FALSE, 
                          aggregate=TRUE, seed=seed)
          prVal <- rbindlist(prVal, idcol="submodel")
          prVal$tfName <- tf
          prVal$computed <- "val_context"
          prVal$holdout_context <- context
          prVal$training_context <- paste(setdiff(contexts, context), collapse=".")
          
          # predict also for validation chromosomes
          predsValChr <- predictTfBinding(mods, fmValChrsIt, chunk=NULL, 
                                          simplified=FALSE, 
                                          BPPARAM=SerialParam())
          predsValChr <- as.data.table(as.matrix(predsValChr[predsValChr[,TFBlearner:::BINLABELNAME]>=0,]))
          prValChr <- lapply(predCols, TFBlearner:::.getPRCurve, 
                             dt=predsValChr, 
                             labels=TFBlearner:::BINLABELNAME, models="context", 
                             posClass=1, negClass=0, subSample=FALSE, 
                             aggregate=TRUE, seed=seed)
          prValChr$tfName <- tf
          prValChr$computed <- "val_chromosomes"
          prValChr$holdout_context <- context
          prValChr$training_context <- paste(setdiff(contexts, context), collapse=".")
          
          # bind iteration results and save
          auprDt <- rbind(prValChr, predsValChr)
          auprDt$ablated_feature_group <- featureGroup
          auprDt$ablated_feature_column_names <- paste(colNamesAbl, collapse="/")
          auprAllDt <- rbind(auprAllDt, auprDt, use.names=TRUE, fill=TRUE)
          write.table(auprAllDt, file=file.path(outDir, "performance_feature_ablation.tsv"),
                      quote=FALSE, row.names=FALSE, sep="\t")
          
          hpDts <- lapply(mods[TFBlearner:::MODELNAMES], function(m){
            params <- m$params[setdiff(names(m$params), 
                                       c("preselMotif", "preselActMotif"))]
            as.data.table(params)})
          hpDt <- rbindlist(hpDts, idcol="submodel")
          hpDt$ablated_feature_group <- featureGroup
          hpDt$ablated_feature_column_names <- paste(colNamesAbl, collapse="/")
          hpAllDt <- rbind(hpAllDt, hpDt, use.names=TRUE, fill=TRUE)
          write.table(hpAllDt, file=file.path(outDir, "hyperparameters_feature_ablation.tsv"),
                      quote=FALSE, row.names=FALSE, sep="\t")
    }
  }
}
```

```{r}
sessionInfo()
```