---
title: "main_DTFA"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r}
suppressPackageStartupMessages({
  library(ComplexHeatmap)
  library(ggplot2)
  library(cowplot)
  library(patchwork)
  library(sechm)
  library(data.table)
  library(ggside)
})
source("../utils/load_all.R", chdir = TRUE)
```

# From ATAC

```{r}
res2 <- readRDS("../07_DTFA/DTFAB_results.rds")

colors <- setNames(c("#0072B2", "#56B4E9", "#E69F00","#D55E00"), levels(res2$method))

pATAC <- ggplot(res2, aes(TF, dev.rank, fill=method)) + geom_col(position=position_dodge()) + scale_y_sqrt(breaks=c(1,10,50,200,600)) + theme_sleek() + 
  ylab("Rank of true TF (lower=better)") + scale_fill_manual(values=colors) + labs(tag="A") +
ggplot(res2, aes(TF, t, fill=method)) + geom_col(position=position_dodge()) + theme_sleek() + ylab("t-value (higher=better)") + scale_y_continuous(transform = signedSqrt) + scale_fill_manual(values=colors) + labs(tags="B") +
ggplot(res2, aes(TF, relAUC, fill=method)) + geom_col(position=position_dodge()) +  theme_sleek() + ylab("Network score (higher=better)") +
  scale_fill_manual(values=colors) + labs(tag="C") + plot_layout(guides="collect") & 
  theme(legend.position = "bottom", axis.title.x = element_blank(),
        axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
```

# From RNA

```{r}
res <- readRDS("../07_DTFA/fromRNA/Nakatake2020/results.rds")
TFlists <- readRDS("../07_DTFA/fromRNA/Nakatake2020/TFlists.rds")
TFlists$perturbed <- intersect(TFlists$perturbed, unlist(lapply(res, \(x) names(x$allRes))))
```

## Results:

```{r}
tt <- as.data.frame(t(sapply(res, \(x) colSums(x$summary[,1:4]))))
tt <- tt[order(-tt$inTop10/tt$isAnnotated),]
tt <- tt[grep("logCPM", row.names(tt)),]
row.names(tt) <- gsub("res_logCPM_","",row.names(tt))
sel <- c("predsReweigh.raw", "proxReweigh.raw", "preds.raw", "collecTRI", "motifs.raw")
tt2 <- tt[sel,]
tt2$method <- newNames <- c("Predictions\n(re-weighed)+Links", "Predictions (re-weighed)\n(Promoters only)", "Predictions\n(raw)+Links","collecTRI", "Motifs+Links")
tt2$method2 <- gsub("\n(Promoters only)","",tt2$method, fixed=TRUE)
tt2$method2 <- gsub(" ","\n",gsub("+Links","",tt2$method2, fixed=TRUE),fixed=TRUE)
tt2$propTop10 <- tt2$inTop10/tt2$isAnnotated
tt2$promoter <- grepl("Promoters", tt2$method)

colors2 <- c(Motifs = "#0072B2", "Predictions\n(re-weighed)" = "#E69F00", "Predictions\n(raw)" = "#D55E00",
             collecTRI = "#CC79A7")

tt3 <- tt2
tt3$inTop10 <- tt3$propTop10
tt3 <- dplyr::bind_rows(list("Number of perturbations\ndetected (in top 10)"=tt2,
                             "Proportion of annotated\nTFs detected (in top 10)"=tt3), .id="type")

p2 <- ggplot(tt3, aes(reorder(method, -inTop10), inTop10, fill=method2, color=promoter)) + 
  geom_col(linetype="dashed") + facet_grid(rows="type", scale="free_y", switch="y") + theme_sleek() + 
  theme(strip.placement = "outside") + labs(x=NULL, y=NULL, fill="Method") +
  scale_color_manual(values=c("FALSE"=NA, "TRUE"="grey40"), guide="none") +
  scale_fill_manual(values=colors2) +
  theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))

# p2 <- (ggplot(tt2, aes(reorder(method, -inTop10), inTop10, fill=method2, color=promoter)) + geom_col() + theme_sleek() + 
#   labs(y="Number of perturbations\ndetected (in top 10)", x=NULL)) /
#   (ggplot(tt2, aes(reorder(method, -propTop10), propTop10, fill=method2, color=promoter)) + geom_col() + theme_sleek() + 
#   labs(y="Proportion of annotated\nTFs detected (in top 10)", x=NULL)) + plot_layout(guides="collect") &
#   scale_color_manual(values=c("FALSE"="#FFFFFF00", "TRUE"="black"), guide="none") &
#   scale_fill_manual(values=colors2) & theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5)) &
#   labs(fill="Method")
```


Direct comparison of TFs found in both:

```{r}
names(x) <- x <- intersect(names(res$res_logCPM_collecTRI$allRes), names(res$res_logCPM_predsReweigh.raw$allRes))
names(y) <- y <- c("res_logCPM_predsReweigh.raw", "res_logCPM_preds.raw", "res_logCPM_collecTRI")
d1 <- dplyr::bind_rows(lapply(x, \(n){
  as.data.frame(lapply(y, \(f){
    a <- which(row.names(res[[f]]$allRes[[n]])==n)
    if(length(a)==0) return(NA_integer_)
    return(min(a))
  }))
}), .id="TF")
d1$type <- factor(as.integer(d1$res_logCPM_predsReweigh.raw<=10) + (10*(d1$res_logCPM_collecTRI<=10)),
                  c(0,1,10,11), c("none","TFBlearner-only", "collecTRI-only", "both"))
p3 <- ggplot(d1[!is.na(d1$type),], aes(res_logCPM_collecTRI, res_logCPM_predsReweigh.raw, label=TF)) + 
  geom_abline(slope=1) + geom_point(aes(color=type)) + 
  ggrepel::geom_text_repel(data=d1[which(d1$res_logCPM_predsReweigh.raw<30 | d1$res_logCPM_collecTRI<30),],
                           min.segment.length = 0, max.overlaps = 30, size=2.5) +
  scale_x_log10() + scale_y_log10() + theme_sleek() + 
  labs(x="collecTRI regulons", y="TFBlearner predictions",
       subtitle="Rank of the perturbed TF (lower=better)")
p3 <- marginalDistributions(p3 + theme(legend.position="bottom"))
```



```{r, fig.width=10, fig.height=10, eval=TRUE}
pdf("main_DTFA.pdf", width=10, height=10)
# plot_grid( plot_grid(pATAC + plot_annotation(title = "Differential TF activity inference from ATAC-seq data")),
#            plot_grid(
#              plot_grid(grid.grabExpr(draw(p1)), grid.grabExpr(draw(p3)),
#                        nrow=2, labels=c("D","F"), rel_heights = c(5,6)),
#              p2 + plot_annotation(title = "  Differential TF activity inference from RNA-seq data") &
#                theme(legend.position="bottom"),
#              rel_widths=c(2,3), labels=c(NA, "E"), scale=c(0.95, 1)),
#            nrow=2, rel_heights = c(2,3)
#            )

p2b <- plot_grid(ggdraw() + draw_label(quote(regulons == preds^T %*% links), size = 13, fontface = "bold"), p2, nrow=2, rel_heights=c(1,8))

pat <- theme(plot.title = element_text(size = 12, face = "bold"))
plot_grid( plot_grid(pATAC + plot_annotation(title = "Differential TF activity inference from ATAC-seq data", theme=pat)),
           ggdraw() + plot_annotation(title = "Differential TF activity inference from RNA-seq data", theme=pat),
           plot_grid(p2b, #p2 +plot_annotation(title = "  Differential TF activity inference from RNA-seq data", theme=pat),
                     p3, nrow=1, scale=0.95, rel_widths=c(5,6), labels=LETTERS[4:5], label_size = 16),
           nrow=3, rel_heights = c(20,3, 30), scale=c(0.95, 0.95, 1)
           )

dev.off()
```